<div class="page-heading"><div><span class="eyebrow">COMMUNITY CARE</span><h1>Report logs</h1><p>A place to review concerns and keep the conversation welcoming.</p></div></div>
<nav class="report-tabs" aria-label="Report menus"><a href="{{ route('reports.index') }}" @class(['active' => $tab === 'logs']) @if($tab === 'logs') aria-current="page" @endif>All reports</a><a href="{{ route('reports.leaderboard') }}" @class(['active' => $tab === 'leaderboard']) @if($tab === 'leaderboard') aria-current="page" @endif>Most reported</a></nav>
<form class="panel report-filters" method="GET" action="{{ $tab === 'logs' ? route('reports.index') : route('reports.leaderboard') }}">
    <label class="field">Search<input type="search" name="q" value="{{ $filters['q'] }}" maxlength="100" placeholder="Content or report description"></label>
    <label class="field">Content type<select name="type">@foreach(['all' => 'All types', 'post' => 'Posts', 'comment' => 'Comments', 'account' => 'Accounts'] as $value => $label)<option value="{{ $value }}" @selected($filters['type'] === $value)>{{ $label }}</option>@endforeach</select></label>
    <label class="field">Severity<select name="severity">@foreach(['all' => 'All severities', 'severe' => 'Severe', 'moderate' => 'Moderate', 'minor' => 'Minor'] as $value => $label)<option value="{{ $value }}" @selected($filters['severity'] === $value)>{{ $label }}</option>@endforeach</select></label>
    <label class="field">Status<select name="status"><option value="all" @selected($filters['status'] === 'all')>All statuses</option><option value="active" @selected($filters['status'] === 'active')>Open + in review</option>@foreach($statuses as $value)<option value="{{ $value }}" @selected($filters['status'] === $value)>{{ ucfirst(str_replace('_', ' ', $value)) }}</option>@endforeach</select></label>
    <label class="field">Reason<select name="reason"><option value="all">All reasons</option>@foreach($groups as $severity => $options)<optgroup label="{{ ucfirst($severity) }}">@foreach($options as $value => $label)<option value="{{ $value }}" @selected($filters['reason'] === $value)>{{ $label }}</option>@endforeach</optgroup>@endforeach</select></label>
    <label class="field">Order<select name="sort">@foreach(($tab === 'leaderboard' ? ['priority' => 'Severity first (default)', 'weighted' => 'Weighted · 100 / 10 / 1', 'total' => 'Most reports', 'newest' => 'Latest report', 'oldest' => 'Oldest first report'] : ['newest' => 'Newest first', 'oldest' => 'Oldest first', 'severity' => 'Severity first']) as $value => $label)<option value="{{ $value }}" @selected($filters['sort'] === $value)>{{ $label }}</option>@endforeach</select></label>
    <label class="field">From (UTC)<input type="date" name="from" value="{{ $filters['from'] }}"></label><label class="field">Through (UTC)<input type="date" name="until" value="{{ $filters['until'] }}"></label>
    @if($filters['target'])<input type="hidden" name="target" value="{{ $filters['target'] }}"><p class="small">Showing {{ $filters['type'] }} #{{ $filters['target'] }}.</p>@endif
    <div class="form-actions"><button class="button" type="submit">Apply filters</button><a class="small" href="{{ $tab === 'logs' ? route('reports.index') : route('reports.leaderboard') }}">Reset filters</a></div>
</form>
