@extends('layouts.site')
@section('title', 'Manage posts')
@section('content')
@php($member = auth()->user())
@php($ownCount = $member->posts()->count())
@php($limit = $member->postLimit())
<div class="page-heading"><div><span class="eyebrow">MAKE SOMEONE'S DAY</span><h1>{{ $member->canModerate() ? 'Manage posts' : 'My posts' }}</h1><p>{{ $member->canModerate() ? 'Publish something funny and keep the community looking good.' : 'Your memes, your little corner of the internet.' }}</p></div><a class="button secondary" href="{{ route('home') }}">View the feed ↗</a></div>
<div class="panel"><h2>Share a meme</h2><p class="muted small">Images, GIFs, and videos welcome. Upload up to 6 files at a time, totaling up to 100 MB.{{ $member->isAdmin() ? ' Admins can also import a ZIP archive.' : '' }}</p><form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">@csrf<div class="form-grid"><label class="field">Title <small>Optional for uploads; original filenames are used when blank.</small><input name="title" value="{{ old('title') }}" maxlength="255" placeholder="Give the internet some context…"></label><label class="field">Your media <small>JPG, PNG, WebP, GIF, MP4, WebM, MOV{{ $member->isAdmin() ? ', ZIP' : '' }}</small><input type="file" name="media[]" multiple required accept="image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm,video/quicktime{{ $member->isAdmin() ? ',.zip' : '' }}"></label></div><div class="quota"><span class="small muted">{{ $ownCount }} {{ $limit === null ? 'posts · unlimited admin access' : 'of '.$limit.' posts used' }}@if($member->hasPremium()) · Premium through {{ $member->premium_expires_at->format('M j, Y') }}@endif</span><button class="button" type="submit">＋ Publish {{ $member->isAdmin() ? '/ import' : '' }}</button></div>@if($limit !== null)<div class="quota-track" role="meter" aria-label="Post limit" aria-valuenow="{{ $ownCount }}" aria-valuemin="0" aria-valuemax="{{ max($ownCount, $limit) }}"><span style="width:{{ min(100, $ownCount / $limit * 100) }}%"></span></div>@if($ownCount >= $limit)<p class="small muted">Your post limit is reached. You can still edit or delete your existing posts.@unless($member->hasPremium()) <a href="{{ route('premium.index') }}">Premium gives you room for 30.</a>@endunless</p>@endif @endif</form></div>
<div class="page-heading"><div><h2 style="margin:0">{{ $member->canModerate() ? 'Community posts' : 'Your published posts' }}</h2><p>{{ $posts->count() }} {{ $posts->count() === 1 ? 'post' : 'posts' }}</p></div></div>
@if($posts->isEmpty())<div class="panel empty-state"><div class="empty-symbol" aria-hidden="true">＋</div><h2>A blank canvas for bad jokes.</h2><p>Choose your first meme above. It will show up here and in the community feed.</p></div>@else
<form id="batch-delete" method="POST" action="{{ route('posts.batchDelete') }}" data-confirm="Permanently delete the selected posts and their reactions?">@csrf @method('DELETE')<div class="form-actions" style="margin:0 0 20px;justify-content:space-between"><label class="manage-selection"><input type="checkbox" data-select-all> Select all</label><button class="button danger small" type="submit">Delete selected</button></div></form>
<div class="dashboard-grid">@foreach($posts as $post)<article class="manage-card"><div class="manage-media">@if($post->media_type === 'video')<video controls playsinline preload="metadata" aria-label="{{ $post->title }}" src="{{ asset('storage/'.$post->media_path) }}"></video>@else<img src="{{ asset('storage/'.$post->media_path) }}" alt="{{ $post->title }}" loading="lazy">@endif</div><div class="manage-info"><span class="badge type">{{ strtoupper($post->media_type) }}</span><h3 style="margin:10px 0">{{ $post->title }}</h3><div class="post-owner"><span>{{ $post->user?->username ?? 'Former member' }}</span><time datetime="{{ $post->created_at->toIso8601String() }}">{{ $post->created_at->format('M j, Y') }}</time></div><div class="form-actions" style="justify-content:space-between;margin-top:10px"><label class="manage-selection"><input type="checkbox" name="post_ids[]" value="{{ $post->id }}" form="batch-delete">Select</label><a class="button secondary small" href="{{ route('posts.edit', $post) }}">Edit post</a></div></div></article>@endforeach</div>
@endif
@endsection